#!/usr/bin/env python3
"""Generate visualisation_pseudo_label.ipynb"""
import json, os, random

def md(src):
    return {"cell_type":"markdown","id":f"{random.randint(0,0xffffffff):08x}","metadata":{},"source":src}
def code(src):
    return {"cell_type":"code","execution_count":None,"id":f"{random.randint(0,0xffffffff):08x}","metadata":{},"outputs":[],"source":src}

cells = []

# ── TITLE ──────────────────────────────────────────────────────────────────
cells.append(md(
    "# Beauty-Axis Pseudo-Label Generation: Step-by-Step Visualization\n\n"
    "Visualizes the complete pipeline from `src/pseudo_labels.py` — **no logic changes**.\n\n"
    "| Step | Description |\n"
    "|------|-------------|\n"
    "| ① | Sample faces per ethnicity subgroup + graph maps |\n"
    "| ② | Population mean face per ethnicity |\n"
    "| ③ | Top-30% highest-rated faces + graph maps |\n"
    "| ④ | Beauty prototype |\n"
    "| ⑤ | Beauty axis (full face + per-organ) |\n"
    "| ⑥ | Test face + graph map |\n"
    "| ⑦ | Per-organ graphs of the test face |\n"
    "| ⑧+⑨ | Per-organ histogram rank + test face position |\n"
    "| ⑩ | Final pseudo-scores per organ |\n"
    "| ⑪ | Geometric projection onto beauty axis (PCA 2D) |\n\n"
    "> **Run cells in order.** Figures saved to `figures/`."
))

# ── COLAB SETUP ────────────────────────────────────────────────────────────
cells.append(md(
    "## Cell 0 : Google Colab Setup\n\n"
    "Mount Drive, copy source `.py` files, and configure all paths.\n\n"
    "> **Edit `DRIVE_ROOT`** if your Drive folder name is different."
))
cells.append(code(
    "from google.colab import drive\n"
    "drive.mount('/content/drive')\n"
    "\n"
    "import os, sys, shutil\n"
    "\n"
    "# ── Edit this to match your Drive folder ────────────────────────────────\n"
    "DRIVE_ROOT = '/content/drive/MyDrive/Colab Notebooks/FaceRankNet8'\n"
    "\n"
    "PROJECT_ROOT = '/content/FaceRankNet'\n"
    "os.makedirs(PROJECT_ROOT, exist_ok=True)\n"
    "\n"
    "# Copy all .py source files from Drive to Colab runtime\n"
    "copied = []\n"
    "for fname in os.listdir(DRIVE_ROOT):\n"
    "    if fname.endswith('.py'):\n"
    "        shutil.copy(os.path.join(DRIVE_ROOT, fname),\n"
    "                    os.path.join(PROJECT_ROOT, fname))\n"
    "        copied.append(fname)\n"
    "if PROJECT_ROOT not in sys.path:\n"
    "    sys.path.insert(0, PROJECT_ROOT)\n"
    "print(f'Copied {len(copied)} .py files: {copied}')\n"
    "\n"
    "CACHE    = f'{DRIVE_ROOT}/cache'\n"
    "CSV      = f'{DRIVE_ROOT}/train_labels.csv'\n"
    "SAVE_DIR = f'{DRIVE_ROOT}/figures'\n"
    "os.makedirs(SAVE_DIR, exist_ok=True)\n"
    "\n"
    "print(f'DRIVE_ROOT : {DRIVE_ROOT}')\n"
    "print(f'CACHE      : {CACHE}')\n"
    "print(f'CSV        : {CSV}')\n"
    "print(f'SAVE_DIR   : {SAVE_DIR}')\n"
))

# ── SETUP ──────────────────────────────────────────────────────────────────
cells.append(code(
    "import pickle, bisect\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib\n"
    "import matplotlib.pyplot as plt\n"
    "import matplotlib.patches as mpatches\n"
    "import matplotlib.gridspec as gridspec\n"
    "from matplotlib.cm import ScalarMappable\n"
    "from matplotlib.colors import Normalize\n"
    "from scipy.spatial.distance import cdist\n"
    "from sklearn.decomposition import PCA\n"
    "import warnings\n"
    "warnings.filterwarnings('ignore')\n"
    "\n"
    "from organ_indices import ORGAN_INDICES\n"
    "from pseudo_labels import (\n"
    "    compute_universal_average_face,\n"
    "    compute_beauty_prototype,\n"
    "    compute_beauty_axis,\n"
    "    project_organ_onto_axis,\n"
    ")\n"
    "\n"
    "ORGAN_COLORS = {\n"
    "    'left_eye':  '#2166AC',\n"
    "    'right_eye': '#4393C3',\n"
    "    'nose':      '#4DAC26',\n"
    "    'mouth':     '#D6604D',\n"
    "    'jawline':   '#762A83',\n"
    "}\n"
    "ORGAN_LABELS = {\n"
    "    'left_eye':  'Left Eye',\n"
    "    'right_eye': 'Right Eye',\n"
    "    'nose':      'Nose',\n"
    "    'mouth':     'Mouth',\n"
    "    'jawline':   'Jawline',\n"
    "}\n"
    "ETH_COLORS = {'Asian': '#2166AC', 'Caucasian': '#D6604D'}\n"
    "\n"
    "plt.rcParams.update({\n"
    "    'font.family'      : 'serif',\n"
    "    'font.serif'       : ['Times New Roman', 'DejaVu Serif', 'Palatino'],\n"
    "    'font.size'        : 9,\n"
    "    'axes.labelsize'   : 9,\n"
    "    'axes.titlesize'   : 9,\n"
    "    'xtick.labelsize'  : 8,\n"
    "    'ytick.labelsize'  : 8,\n"
    "    'legend.fontsize'  : 8,\n"
    "    'legend.frameon'   : True,\n"
    "    'legend.framealpha': 0.9,\n"
    "    'legend.edgecolor' : '0.8',\n"
    "    'axes.linewidth'   : 0.7,\n"
    "    'axes.spines.top'  : False,\n"
    "    'axes.spines.right': False,\n"
    "    'xtick.major.width': 0.7,\n"
    "    'ytick.major.width': 0.7,\n"
    "    'lines.linewidth'  : 1.0,\n"
    "    'patch.linewidth'  : 0.5,\n"
    "    'grid.linewidth'   : 0.4,\n"
    "    'grid.color'       : '0.88',\n"
    "    'figure.dpi'       : 150,\n"
    "    'savefig.dpi'      : 300,\n"
    "    'savefig.bbox'     : 'tight',\n"
    "})\n"
    "\n"
    "def get_eth(f): return 'Asian' if f[0].upper() == 'A' else 'Caucasian'\n"
    "def get_gen(f): return 'Female' if f[1].upper() == 'F' else 'Male'\n"
    "def fxy(c):     return c[:, 0], -c[:, 1]\n"
    "\n"
    "print('Setup complete.')\n"
    "print(f'  Organs   : {list(ORGAN_INDICES.keys())}')\n"
    "print(f'  Save dir : {SAVE_DIR}')"
))

# ── LOAD DATA ──────────────────────────────────────────────────────────────
cells.append(code(
    "# CACHE, CSV, SAVE_DIR are defined in Cell 0 (Colab Setup)\n"
    "with open(f'{CACHE}/train_landmarks.pkl', 'rb') as fh:\n"
    "    coords_cache = pickle.load(fh)\n"
    "with open(f'{CACHE}/pseudo_labels.pkl', 'rb') as fh:\n"
    "    pseudo_labels_ref = pickle.load(fh)\n"
    "avg_face_ref = np.load(f'{CACHE}/avg_face.npy')\n"
    "\n"
    "df           = pd.read_csv(CSV)\n"
    "train_fnames = df['Filename'].tolist()\n"
    "hol_ratings  = dict(zip(df['Filename'], df['Rating'].astype(float)))\n"
    "# Use Ethnicity column if present, else derive from filename prefix\n"
    "if 'Ethnicity' in df.columns:\n"
    "    eth_map = dict(zip(df['Filename'], df['Ethnicity']))\n"
    "    def get_eth(f): return eth_map.get(f, 'Asian' if f[0].upper()=='A' else 'Caucasian')\n"
    "if 'Gender' in df.columns:\n"
    "    gen_map = dict(zip(df['Filename'], df['Gender']))\n"
    "    def get_gen(f): return gen_map.get(f, 'Female' if f[1].upper()=='F' else 'Male')\n"
    "valid_train  = [f for f in train_fnames if f in coords_cache]\n"
    "\n"
    "pop_mean    = {}\n"
    "beauty_proto = {}\n"
    "for eth in ['Asian', 'Caucasian']:\n"
    "    eth_fnames  = [f for f in valid_train if get_eth(f) == eth]\n"
    "    eth_coords  = [coords_cache[f] for f in eth_fnames]\n"
    "    eth_ratings = [hol_ratings[f] for f in eth_fnames]\n"
    "    pop_mean[eth]     = compute_universal_average_face(eth_coords)\n"
    "    beauty_proto[eth] = compute_beauty_prototype(eth_coords, eth_ratings, top_k_pct=0.30)\n"
    "\n"
    "beauty_axis = {\n"
    "    eth: compute_beauty_axis(pop_mean[eth], beauty_proto[eth])\n"
    "    for eth in pop_mean\n"
    "}\n"
    "pop_mean_global = compute_universal_average_face(\n"
    "    [coords_cache[f] for f in valid_train]\n"
    ")\n"
    "\n"
    "organ_projs = {o: [] for o in ORGAN_INDICES}\n"
    "proj_fnames = []\n"
    "for fname in valid_train:\n"
    "    eth  = get_eth(fname)\n"
    "    mu   = pop_mean[eth]\n"
    "    axis = beauty_axis[eth]\n"
    "    proj_fnames.append(fname)\n"
    "    for organ, idxs in ORGAN_INDICES.items():\n"
    "        p = project_organ_onto_axis(coords_cache[fname], mu, axis, idxs)\n"
    "        organ_projs[organ].append(p)\n"
    "\n"
    "organ_sorted = {o: sorted(v) for o, v in organ_projs.items()}\n"
    "\n"
    "print(f'Loaded {len(coords_cache)} faces  |  valid_train: {len(valid_train)}')\n"
    "for eth in ['Asian', 'Caucasian']:\n"
    "    n     = sum(1 for f in valid_train if get_eth(f) == eth)\n"
    "    n_top = max(1, int(n * 0.30))\n"
    "    print(f'  {eth:<12}: {n} faces  |  top-30% = {n_top}')\n"
    "print('Projections computed.')"
))

# ── HELPERS ────────────────────────────────────────────────────────────────
cells.append(code(
    "JAWLINE = [10,338,297,332,284,251,389,356,454,323,361,288,\n"
    "           397,365,379,378,400,377,152,148,176,149,150,136,\n"
    "           172,58,132,93,234,127,162,21,54,103,67,109]\n"
    "L_EYE   = [33,7,163,144,145,153,154,155,133,173,157,158,159,160,161,246]\n"
    "R_EYE   = [362,382,381,380,374,373,390,249,263,466,388,387,386,385,384,398]\n"
    "L_BROW  = [46,53,52,65,55,70,63,105,66,107]\n"
    "R_BROW  = [276,283,282,295,285,300,293,334,296,336]\n"
    "NOSE_B  = [168,197,195,5,4,1]\n"
    "M_OUT   = [61,146,91,181,84,17,314,405,321,375,291,409,270,269,267,0,37,39,40,185]\n"
    "M_IN    = [78,95,88,178,87,14,317,402,318,324,308,415,310,311,312,13,82,81,80,191]\n"
    "\n"
    "\n"
    "def _path(ax, c, idx, col, lw=0.8, alpha=0.5, close=False):\n"
    "    v = [i for i in idx if 0 <= i < 468]\n"
    "    if len(v) < 2:\n"
    "        return\n"
    "    x, y = fxy(c)\n"
    "    px, py = x[v], y[v]\n"
    "    if close:\n"
    "        px = np.append(px, px[0])\n"
    "        py = np.append(py, py[0])\n"
    "    ax.plot(px, py, color=col, lw=lw, alpha=alpha, zorder=2)\n"
    "\n"
    "\n"
    "def draw_face(ax, c, title='', hl=None, ms=3, alpha_bg=0.15):\n"
    "    x, y = fxy(c)\n"
    "    _path(ax, c, JAWLINE, '#BBBBBB', lw=1.0, alpha=0.65, close=True)\n"
    "    _path(ax, c, L_EYE,  ORGAN_COLORS['left_eye'],  lw=0.9, alpha=0.60, close=True)\n"
    "    _path(ax, c, R_EYE,  ORGAN_COLORS['right_eye'], lw=0.9, alpha=0.60, close=True)\n"
    "    _path(ax, c, L_BROW, ORGAN_COLORS['left_eye'],  lw=0.7, alpha=0.40)\n"
    "    _path(ax, c, R_BROW, ORGAN_COLORS['right_eye'], lw=0.7, alpha=0.40)\n"
    "    _path(ax, c, NOSE_B, ORGAN_COLORS['nose'],  lw=0.8, alpha=0.50)\n"
    "    _path(ax, c, M_OUT,  ORGAN_COLORS['mouth'], lw=0.9, alpha=0.60, close=True)\n"
    "    _path(ax, c, M_IN,   ORGAN_COLORS['mouth'], lw=0.5, alpha=0.30, close=True)\n"
    "    for organ, idxs in ORGAN_INDICES.items():\n"
    "        v  = [i for i in idxs if 0 <= i < 468]\n"
    "        a  = 1.0 if hl is None or hl == organ else alpha_bg\n"
    "        sz = (ms * 2.2)**2 if hl == organ else ms**2\n"
    "        ax.scatter(x[v], y[v], c=ORGAN_COLORS[organ], s=sz,\n"
    "                   alpha=a, zorder=3, linewidths=0)\n"
    "    ax.set_aspect('equal')\n"
    "    ax.set_xticks([]); ax.set_yticks([])\n"
    "    for sp in ax.spines.values():\n"
    "        sp.set_visible(False)\n"
    "    if title:\n"
    "        ax.set_title(title, fontsize=9, pad=3)\n"
    "\n"
    "\n"
    "def draw_organ(ax, c, organ, title='', color=None, ms=5, padding=0.35):\n"
    "    col  = color or ORGAN_COLORS[organ]\n"
    "    idxs = [i for i in ORGAN_INDICES[organ] if 0 <= i < 468]\n"
    "    x, y = fxy(c)\n"
    "    px, py = x[idxs], y[idxs]\n"
    "    pts = np.column_stack([px, py])\n"
    "    if len(pts) > 2:\n"
    "        D = cdist(pts, pts)\n"
    "        np.fill_diagonal(D, np.inf)\n"
    "        k   = min(3, len(pts) - 1)\n"
    "        thr = np.percentile(D[D < np.inf], 22)\n"
    "        for i in range(len(pts)):\n"
    "            for j in np.argsort(D[i])[:k]:\n"
    "                if D[i, j] <= thr * 1.5:\n"
    "                    ax.plot([px[i], px[j]], [py[i], py[j]],\n"
    "                            color=col, lw=1.2, alpha=0.4, zorder=2)\n"
    "    ax.scatter(px, py, c=col, s=ms**2, alpha=0.95, zorder=3,\n"
    "               edgecolors='white', linewidths=0.4)\n"
    "    if len(px) > 0:\n"
    "        xr = max(px.ptp(), 1e-6)\n"
    "        yr = max(py.ptp(), 1e-6)\n"
    "        m  = max(xr, yr) * padding\n"
    "        ax.set_xlim(px.min() - m, px.max() + m)\n"
    "        ax.set_ylim(py.min() - m, py.max() + m)\n"
    "    ax.set_aspect('equal')\n"
    "    ax.set_xticks([]); ax.set_yticks([])\n"
    "    for sp in ax.spines.values():\n"
    "        sp.set_visible(False)\n"
    "    ttl = title or ORGAN_LABELS.get(organ, organ)\n"
    "    ax.set_title(ttl, fontsize=9, pad=3, color=col, fontweight='bold')\n"
    "\n"
    "\n"
    "print('Helpers ready.')"
))

# ── STEP 1a: ETHNICITY SAMPLES ─────────────────────────────────────────────
cells.append(md(
    "## Step ① : Sample Faces per Ethnicity Subgroup\n\n"
    "Shows 6 sample faces spanning the rating range (low → high) for each ethnicity."
))
cells.append(code(
    "np.random.seed(42)\n"
    "ETH_LIST = ['Asian', 'Caucasian']\n"
    "\n"
    "fig, axes = plt.subplots(2, 6, figsize=(16, 6.5))\n"
    "fig.suptitle(\n"
    "    'Step ①  |  Sample Faces per Ethnicity Subgroup\\n'\n"
    "    '(MediaPipe FaceMesh 468 landmarks — color-coded by organ)',\n"
    "    fontsize=9, fontweight='bold', y=1.02)\n"
    "\n"
    "for row, eth in enumerate(ETH_LIST):\n"
    "    eth_fnames = sorted([f for f in valid_train if get_eth(f) == eth],\n"
    "                        key=lambda f: hol_ratings[f])\n"
    "    n = len(eth_fnames)\n"
    "    picks = [eth_fnames[int(n * q)] for q in [0.05, 0.20, 0.40, 0.60, 0.80, 0.95]]\n"
    "    for col, fname in enumerate(picks):\n"
    "        ax = axes[row, col]\n"
    "        draw_face(ax, coords_cache[fname], ms=2.5)\n"
    "        ax.set_title(f'Rating: {hol_ratings[fname]:.2f}', fontsize=8, pad=2,\n"
    "                     color=ETH_COLORS[eth])\n"
    "        if col == 0:\n"
    "            ax.set_ylabel(eth, fontsize=11, fontweight='bold',\n"
    "                          color=ETH_COLORS[eth], labelpad=4)\n"
    "        ax.set_facecolor('#F5F9FF' if eth == 'Asian' else '#FFF8F0')\n"
    "\n"
    "patches = [mpatches.Patch(facecolor=ORGAN_COLORS[o], label=ORGAN_LABELS[o])\n"
    "           for o in ORGAN_INDICES]\n"
    "fig.legend(handles=patches, loc='lower center', ncol=5, fontsize=9,\n"
    "           bbox_to_anchor=(0.5, -0.04), frameon=True, framealpha=0.9)\n"
    "plt.tight_layout(h_pad=2.0, w_pad=0.4)\n"
    "plt.savefig(f'{SAVE_DIR}/step1a_ethnicity_samples.pdf')\n"
    "plt.savefig(f'{SAVE_DIR}/step1a_ethnicity_samples.png')\n"
    "plt.show()\n"
    "print('Saved: step1a_ethnicity_samples.pdf + .png')"
))

# ── STEP 1b: GRAPH MAPS ────────────────────────────────────────────────────
cells.append(code(
    "# Graph maps (transparent background, for overlay on actual face photos)\n"
    "fig, axes = plt.subplots(2, 3, figsize=(9, 7))\n"
    "fig.patch.set_alpha(0.0)\n"
    "fig.suptitle('Step ①b  |  Graph Maps (transparent — overlay on real photos)',\n"
    "             fontsize=11, fontweight='bold')\n"
    "\n"
    "for row, eth in enumerate(ETH_LIST):\n"
    "    eth_fnames = sorted([f for f in valid_train if get_eth(f) == eth],\n"
    "                        key=lambda f: hol_ratings[f])\n"
    "    n = len(eth_fnames)\n"
    "    picks = [eth_fnames[int(n * 0.20)], eth_fnames[n // 2], eth_fnames[int(n * 0.85)]]\n"
    "    for col, fname in enumerate(picks):\n"
    "        ax = axes[row, col]\n"
    "        ax.set_facecolor('none')\n"
    "        x, y = fxy(coords_cache[fname])\n"
    "        for organ, idxs in ORGAN_INDICES.items():\n"
    "            v = [i for i in idxs if 0 <= i < 468]\n"
    "            ax.scatter(x[v], y[v], c=ORGAN_COLORS[organ], s=10,\n"
    "                       alpha=0.95, zorder=3, linewidths=0)\n"
    "        _path(ax, coords_cache[fname], JAWLINE, '#777777', lw=1.0, alpha=0.55, close=True)\n"
    "        _path(ax, coords_cache[fname], L_EYE,  ORGAN_COLORS['left_eye'],  lw=1.0, alpha=0.75, close=True)\n"
    "        _path(ax, coords_cache[fname], R_EYE,  ORGAN_COLORS['right_eye'], lw=1.0, alpha=0.75, close=True)\n"
    "        _path(ax, coords_cache[fname], M_OUT,  ORGAN_COLORS['mouth'],     lw=1.0, alpha=0.75, close=True)\n"
    "        _path(ax, coords_cache[fname], NOSE_B, ORGAN_COLORS['nose'],      lw=0.9, alpha=0.65)\n"
    "        ax.set_aspect('equal'); ax.set_xticks([]); ax.set_yticks([])\n"
    "        for sp in ax.spines.values(): sp.set_visible(False)\n"
    "        ax.set_title(f'{eth}  •  Rating {hol_ratings[fname]:.2f}',\n"
    "                     fontsize=8, pad=2, color=ETH_COLORS[eth])\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(f'{SAVE_DIR}/step1b_graph_maps.png', transparent=True)\n"
    "plt.show()\n"
    "print('Saved: step1b_graph_maps.png (transparent)')"
))

# ── STEP 2: POPULATION MEAN ────────────────────────────────────────────────
cells.append(md(
    "## Step ② : Population Mean per Ethnicity\n\n"
    "`population_mean_e = mean(all train coords | ethnicity = e)` — the centroid of face-space."
))
cells.append(code(
    "fig, axes = plt.subplots(1, 3, figsize=(13, 5.5))\n"
    "fig.suptitle(\n"
    "    'Step ②  |  Population Mean Face per Ethnicity\\n'\n"
    "    'population_mean_e = mean( all train coords | ethnicity = e )',\n"
    "    fontsize=9, fontweight='bold', y=1.02)\n"
    "\n"
    "draw_face(axes[0], pop_mean_global, ms=3)\n"
    "axes[0].set_title('Global Mean\\n(all ethnicities)', fontsize=9, fontweight='bold', pad=5)\n"
    "axes[0].set_facecolor('#F0F4F8')\n"
    "\n"
    "for col, eth in enumerate(['Asian', 'Caucasian'], start=1):\n"
    "    draw_face(axes[col], pop_mean[eth], ms=3)\n"
    "    n = sum(1 for f in valid_train if get_eth(f) == eth)\n"
    "    axes[col].set_title(f'{eth} Mean\\n(n = {n} faces)',\n"
    "                        fontsize=10, fontweight='bold', pad=5, color=ETH_COLORS[eth])\n"
    "    axes[col].set_facecolor('#F8F9FA')\n"
    "\n"
    "plt.tight_layout(w_pad=2.0)\n"
    "plt.savefig(f'{SAVE_DIR}/step2_population_mean.pdf')\n"
    "plt.savefig(f'{SAVE_DIR}/step2_population_mean.png')\n"
    "plt.show()\n"
    "print('Saved: step2_population_mean.pdf + .png')"
))

# ── STEP 3: TOP FACES ─────────────────────────────────────────────────────
cells.append(md(
    "## Step ③ : Top-30% Highest-Rated Faces per Ethnicity\n\n"
    "These are the training faces whose holistic beauty rating places them in the **top 30%**. "
    "Their mean becomes the **beauty prototype**."
))
cells.append(code(
    "fig, axes = plt.subplots(2, 6, figsize=(16, 6.5))\n"
    "fig.suptitle(\n"
    "    'Step ③  |  Top-30% Highest-Rated Faces per Ethnicity\\n'\n"
    "    '(These faces define the beauty_prototype_e)',\n"
    "    fontsize=9, fontweight='bold', y=1.02)\n"
    "\n"
    "for row, eth in enumerate(ETH_LIST):\n"
    "    eth_fnames  = [f for f in valid_train if get_eth(f) == eth]\n"
    "    eth_ratings = [hol_ratings[f] for f in eth_fnames]\n"
    "    n_top = max(1, int(len(eth_fnames) * 0.30))\n"
    "    top_idx    = np.argsort(eth_ratings)[::-1]\n"
    "    top_fnames = [eth_fnames[i] for i in top_idx[:6]]\n"
    "    for col, fname in enumerate(top_fnames):\n"
    "        ax = axes[row, col]\n"
    "        draw_face(ax, coords_cache[fname], ms=2.5)\n"
    "        star = '★' if col == 0 else ''\n"
    "        ax.set_title(f'{star}#{col+1}: {hol_ratings[fname]:.2f}',\n"
    "                     fontsize=8, pad=2, color=ETH_COLORS[eth])\n"
    "        if col == 0:\n"
    "            ax.set_ylabel(f'{eth}\\n(top-{n_top})', fontsize=9,\n"
    "                          fontweight='bold', color=ETH_COLORS[eth])\n"
    "        ax.set_facecolor('#FFFEF0')\n"
    "\n"
    "patches = [mpatches.Patch(facecolor=ORGAN_COLORS[o], label=ORGAN_LABELS[o])\n"
    "           for o in ORGAN_INDICES]\n"
    "fig.legend(handles=patches, loc='lower center', ncol=5, fontsize=9,\n"
    "           bbox_to_anchor=(0.5, -0.04))\n"
    "plt.tight_layout(h_pad=2.0, w_pad=0.3)\n"
    "plt.savefig(f'{SAVE_DIR}/step3_top_faces.pdf')\n"
    "plt.savefig(f'{SAVE_DIR}/step3_top_faces.png')\n"
    "plt.show()\n"
    "print('Saved: step3_top_faces.pdf + .png')"
))

# ── STEP 4: BEAUTY PROTOTYPE ───────────────────────────────────────────────
cells.append(md(
    "## Step ④ : Beauty Prototype\n\n"
    "`beauty_prototype_e = mean(top-30% rated face coords | ethnicity = e)`\n\n"
    "Right panel: overlay of population mean (faint circles) vs beauty prototype (bright stars) for Asian."
))
cells.append(code(
    "fig, axes = plt.subplots(1, 3, figsize=(13, 5.5))\n"
    "fig.suptitle(\n"
    "    'Step ④  |  Beauty Prototype per Ethnicity\\n'\n"
    "    'beauty_prototype_e = mean( top-30% rated face coords | ethnicity = e )',\n"
    "    fontsize=9, fontweight='bold', y=1.02)\n"
    "\n"
    "for col, eth in enumerate(['Asian', 'Caucasian']):\n"
    "    draw_face(axes[col], beauty_proto[eth], ms=3)\n"
    "    n_top = max(1, int(sum(1 for f in valid_train if get_eth(f) == eth) * 0.30))\n"
    "    axes[col].set_title(f'{eth} Beauty Prototype\\n(mean of top-{n_top} faces)',\n"
    "                        fontsize=9, fontweight='bold', color=ETH_COLORS[eth], pad=5)\n"
    "    axes[col].set_facecolor('#FFFBF0')\n"
    "\n"
    "# Overlay comparison (Asian)\n"
    "ax  = axes[2]\n"
    "eth = 'Asian'\n"
    "xm, ym = fxy(pop_mean[eth])\n"
    "xp, yp = fxy(beauty_proto[eth])\n"
    "for organ, idxs in ORGAN_INDICES.items():\n"
    "    v = [i for i in idxs if 0 <= i < 468]\n"
    "    c = ORGAN_COLORS[organ]\n"
    "    ax.scatter(xm[v], ym[v], color=c, s=7,  alpha=0.28, zorder=2, marker='o')\n"
    "    ax.scatter(xp[v], yp[v], color=c, s=25, alpha=0.95, zorder=4, marker='*')\n"
    "_path(ax, pop_mean[eth],    JAWLINE, '#CCCCCC', lw=1.0, alpha=0.40, close=True)\n"
    "_path(ax, beauty_proto[eth], JAWLINE, ETH_COLORS[eth], lw=1.2, alpha=0.65, close=True)\n"
    "ax.set_aspect('equal'); ax.set_xticks([]); ax.set_yticks([])\n"
    "for sp in ax.spines.values(): sp.set_visible(False)\n"
    "from matplotlib.lines import Line2D\n"
    "leg = [\n"
    "    Line2D([0],[0], marker='o', color='w', markerfacecolor='gray', ms=6,\n"
    "           alpha=0.4, label='Population Mean'),\n"
    "    Line2D([0],[0], marker='*', color='w', markerfacecolor='gold', ms=10,\n"
    "           label='Beauty Prototype'),\n"
    "]\n"
    "ax.legend(handles=leg, fontsize=8, loc='lower center', framealpha=0.9)\n"
    "ax.set_title('Asian: Mean ◦ vs Prototype ★\\n(overlay)', fontsize=9,\n"
    "             fontweight='bold', pad=5)\n"
    "ax.set_facecolor('#F8F4FF')\n"
    "\n"
    "plt.tight_layout(w_pad=2.0)\n"
    "plt.savefig(f'{SAVE_DIR}/step4_beauty_prototype.pdf')\n"
    "plt.savefig(f'{SAVE_DIR}/step4_beauty_prototype.png')\n"
    "plt.show()\n"
    "print('Saved: step4_beauty_prototype.pdf + .png')"
))

# ── STEP 5a: BEAUTY AXIS FULL ─────────────────────────────────────────────
cells.append(md(
    "## Step ⑤ : Beauty Axis\n\n"
    "`beauty_axis_e = beauty_prototype_e − population_mean_e`\n\n"
    "A (468×3) vector field pointing from the average face toward the attractive end of face-space. "
    "Arrows show the per-landmark shift direction."
))
cells.append(code(
    "fig, axes = plt.subplots(1, 2, figsize=(12, 6.5))\n"
    "fig.suptitle(\n"
    "    'Step ⑤a  |  Beauty Axis: beauty_prototype_e − population_mean_e\\n'\n"
    "    'Arrows = direction each landmark shifts toward the attractive pole',\n"
    "    fontsize=9, fontweight='bold', y=1.02)\n"
    "\n"
    "for col, eth in enumerate(ETH_LIST):\n"
    "    ax    = axes[col]\n"
    "    mu    = pop_mean[eth]\n"
    "    proto = beauty_proto[eth]\n"
    "    axis  = beauty_axis[eth]\n"
    "    xm, ym = fxy(mu)\n"
    "    xp, yp = fxy(proto)\n"
    "    xa = axis[:, 0]; ya = -axis[:, 1]\n"
    "\n"
    "    # Population mean (faint)\n"
    "    for organ, idxs in ORGAN_INDICES.items():\n"
    "        v = [i for i in idxs if 0 <= i < 468]\n"
    "        ax.scatter(xm[v], ym[v], c=ORGAN_COLORS[organ], s=4,\n"
    "                   alpha=0.25, zorder=2, linewidths=0)\n"
    "    _path(ax, mu, JAWLINE, '#CCCCCC', lw=1.0, alpha=0.45, close=True)\n"
    "\n"
    "    # Arrows\n"
    "    mags  = np.sqrt(xa**2 + ya**2)\n"
    "    scale = 0.35 / (mags.max() + 1e-9)\n"
    "    for i in range(0, 468, 12):\n"
    "        if mags[i] > mags.mean() * 0.6:\n"
    "            ax.annotate('',\n"
    "                        xy=(xm[i] + xa[i]*scale, ym[i] + ya[i]*scale),\n"
    "                        xytext=(xm[i], ym[i]),\n"
    "                        arrowprops=dict(arrowstyle='->', color='#FF6B35',\n"
    "                                        lw=0.9, alpha=0.65))\n"
    "\n"
    "    # Beauty prototype (bright)\n"
    "    for organ, idxs in ORGAN_INDICES.items():\n"
    "        v = [i for i in idxs if 0 <= i < 468]\n"
    "        ax.scatter(xp[v], yp[v], c=ORGAN_COLORS[organ], s=14,\n"
    "                   alpha=0.90, zorder=4, marker='*', linewidths=0)\n"
    "    _path(ax, proto, JAWLINE, ETH_COLORS[eth], lw=1.3, alpha=0.70, close=True)\n"
    "\n"
    "    ax.set_aspect('equal'); ax.set_xticks([]); ax.set_yticks([])\n"
    "    for sp in ax.spines.values(): sp.set_visible(False)\n"
    "    ax.set_title(\n"
    "        f'{eth} Beauty Axis\\n'\n"
    "        'faint = mean  |  bright ★ = prototype  |  → = beauty axis direction',\n"
    "        fontsize=9, fontweight='bold', color=ETH_COLORS[eth], pad=5)\n"
    "    ax.set_facecolor('#F8F9FA')\n"
    "    from matplotlib.lines import Line2D\n"
    "    leg = [\n"
    "        Line2D([0],[0], marker='o', color='w', markerfacecolor='gray',\n"
    "               ms=6, alpha=0.4, label='Population Mean'),\n"
    "        Line2D([0],[0], marker='*', color='w', markerfacecolor='gold',\n"
    "               ms=10, label='Beauty Prototype'),\n"
    "        mpatches.Patch(color='#FF6B35', alpha=0.7, label='Beauty Axis →'),\n"
    "    ]\n"
    "    ax.legend(handles=leg, fontsize=7.5, loc='lower center', framealpha=0.9)\n"
    "\n"
    "plt.tight_layout(w_pad=2.5)\n"
    "plt.savefig(f'{SAVE_DIR}/step5a_beauty_axis_full.pdf')\n"
    "plt.savefig(f'{SAVE_DIR}/step5a_beauty_axis_full.png')\n"
    "plt.show()\n"
    "print('Saved: step5a_beauty_axis_full.pdf + .png')"
))

# ── STEP 5b: PER-ORGAN AXIS ───────────────────────────────────────────────
cells.append(code(
    "# Per-organ beauty axis (Asian example)\n"
    "eth   = 'Asian'\n"
    "mu_5b = pop_mean[eth]\n"
    "proto_5b = beauty_proto[eth]\n"
    "axis_5b  = beauty_axis[eth]\n"
    "xm5, ym5 = fxy(mu_5b)\n"
    "xp5, yp5 = fxy(proto_5b)\n"
    "xa5 = axis_5b[:, 0]; ya5 = -axis_5b[:, 1]\n"
    "mags5 = np.sqrt(xa5**2 + ya5**2)\n"
    "\n"
    "fig, axes = plt.subplots(1, 5, figsize=(16, 4.5))\n"
    "fig.suptitle(\n"
    "    'Step ⑤b  |  Per-Organ Beauty Axis  (ethnicity: Asian)\\n'\n"
    "    'beauty_axis_e[o] = organ-restricted subvector '\n"
    "    'of (beauty_prototype_e − population_mean_e)',\n"
    "    fontsize=9, fontweight='bold', y=1.02)\n"
    "\n"
    "for col, organ in enumerate(ORGAN_INDICES.keys()):\n"
    "    ax    = axes[col]\n"
    "    idxs  = [i for i in ORGAN_INDICES[organ] if 0 <= i < 468]\n"
    "    col_o = ORGAN_COLORS[organ]\n"
    "    pxm, pym = xm5[idxs], ym5[idxs]\n"
    "    pxp, pyp = xp5[idxs], yp5[idxs]\n"
    "    pxa, pya = xa5[idxs], ya5[idxs]\n"
    "    pmag = mags5[idxs]\n"
    "\n"
    "    # Mean dots + connections\n"
    "    pts = np.column_stack([pxm, pym])\n"
    "    if len(pts) > 2:\n"
    "        D = cdist(pts, pts); np.fill_diagonal(D, np.inf)\n"
    "        thr = np.percentile(D[D<np.inf], 22)\n"
    "        for i in range(len(pts)):\n"
    "            for j in np.argsort(D[i])[:2]:\n"
    "                if D[i,j] <= thr*1.5:\n"
    "                    ax.plot([pxm[i],pxm[j]], [pym[i],pym[j]],\n"
    "                            color='#AAAAAA', lw=0.8, alpha=0.4, zorder=1)\n"
    "    ax.scatter(pxm, pym, c='#AAAAAA', s=28, alpha=0.55, zorder=2,\n"
    "               edgecolors='white', linewidths=0.3, label='Mean')\n"
    "\n"
    "    # Arrows\n"
    "    sc = 0.25 / (pmag.max() + 1e-9)\n"
    "    for i in range(len(idxs)):\n"
    "        if pmag[i] > pmag.mean() * 0.4:\n"
    "            ax.annotate('',\n"
    "                        xy=(pxm[i]+pxa[i]*sc, pym[i]+pya[i]*sc),\n"
    "                        xytext=(pxm[i], pym[i]),\n"
    "                        arrowprops=dict(arrowstyle='->', color='#FF6B35',\n"
    "                                        lw=0.9, alpha=0.75))\n"
    "\n"
    "    # Prototype stars\n"
    "    ax.scatter(pxp, pyp, c=col_o, s=60, alpha=0.92, zorder=4,\n"
    "               edgecolors='white', linewidths=0.5, marker='*', label='Prototype')\n"
    "\n"
    "    all_x = np.concatenate([pxm, pxp])\n"
    "    all_y = np.concatenate([pym, pyp])\n"
    "    xpad  = max(all_x.ptp(), 1e-6) * 0.55\n"
    "    ypad  = max(all_y.ptp(), 1e-6) * 0.55\n"
    "    ax.set_xlim(all_x.min()-xpad, all_x.max()+xpad)\n"
    "    ax.set_ylim(all_y.min()-ypad, all_y.max()+ypad)\n"
    "    ax.set_aspect('equal'); ax.set_xticks([]); ax.set_yticks([])\n"
    "    for sp in ax.spines.values(): sp.set_visible(False)\n"
    "    ax.set_title(f'{ORGAN_LABELS[organ]}\\n({len(idxs)} nodes)',\n"
    "                 fontsize=9, color=col_o, fontweight='bold', pad=3)\n"
    "    if col == 0:\n"
    "        ax.legend(fontsize=7, loc='upper left', framealpha=0.9, handlelength=1.2)\n"
    "\n"
    "plt.tight_layout(w_pad=0.5)\n"
    "plt.savefig(f'{SAVE_DIR}/step5b_beauty_axis_organs.pdf')\n"
    "plt.savefig(f'{SAVE_DIR}/step5b_beauty_axis_organs.png')\n"
    "plt.show()\n"
    "print('Saved: step5b_beauty_axis_organs.pdf + .png')"
))

# ── STEP 6: TEST FACE ─────────────────────────────────────────────────────
cells.append(md(
    "## Step ⑥ : Select a Test Face\n\n"
    "One training face is selected to demonstrate the full per-organ projection pipeline."
))
cells.append(code(
    "np.random.seed(7)\n"
    "asian_sorted = sorted([f for f in valid_train if get_eth(f) == 'Asian'],\n"
    "                      key=lambda f: hol_ratings[f])\n"
    "n_a = len(asian_sorted)\n"
    "demo_fname = asian_sorted[int(n_a * 0.72)]\n"
    "\n"
    "demo_eth  = get_eth(demo_fname)\n"
    "demo_mu   = pop_mean[demo_eth]\n"
    "demo_axis = beauty_axis[demo_eth]\n"
    "\n"
    "demo_projs  = {}\n"
    "demo_scores = {}\n"
    "for organ, idxs in ORGAN_INDICES.items():\n"
    "    proj = project_organ_onto_axis(coords_cache[demo_fname], demo_mu, demo_axis, idxs)\n"
    "    demo_projs[organ] = proj\n"
    "    rank  = bisect.bisect_left(organ_sorted[organ], proj) / len(organ_projs[organ])\n"
    "    demo_scores[organ] = float(np.clip(1.0 + 4.0 * rank, 1.0, 5.0))\n"
    "\n"
    "print(f'Demo face   : {demo_fname}')\n"
    "print(f'Ethnicity   : {demo_eth}')\n"
    "print(f'GT Rating   : {hol_ratings[demo_fname]:.3f}')\n"
    "print(f'Mean pseudo : {np.mean(list(demo_scores.values())):.3f}')\n"
    "print()\n"
    "print(f'{\"Organ\":<14} {\"Projection\":>12}  {\"Rank\":>8}  {\"Score\":>7}')\n"
    "print('-' * 46)\n"
    "for organ in ORGAN_INDICES:\n"
    "    proj = demo_projs[organ]\n"
    "    rank = bisect.bisect_left(organ_sorted[organ], proj) / len(organ_projs[organ])\n"
    "    print(f'{ORGAN_LABELS[organ]:<14} {proj:>12.4f}  {rank:>7.2%}  {demo_scores[organ]:>7.2f}')\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(11, 5.5))\n"
    "fig.suptitle(\n"
    "    f'Step ⑥  |  Test Face: {demo_fname}\\n'\n"
    "    f'GT Rating = {hol_ratings[demo_fname]:.3f}  |  Ethnicity: {demo_eth}',\n"
    "    fontsize=9, fontweight='bold')\n"
    "\n"
    "draw_face(axes[0], coords_cache[demo_fname], ms=3)\n"
    "axes[0].set_title('Full Face Landmark Graph\\n(color-coded by organ region)', fontsize=9, loc='left')\n"
    "axes[0].set_facecolor('#F8F9FA')\n"
    "\n"
    "ax = axes[1]\n"
    "ax.set_facecolor('none')\n"
    "x, y = fxy(coords_cache[demo_fname])\n"
    "for organ, idxs in ORGAN_INDICES.items():\n"
    "    v = [i for i in idxs if 0 <= i < 468]\n"
    "    ax.scatter(x[v], y[v], c=ORGAN_COLORS[organ], s=12, alpha=0.95, zorder=3, linewidths=0)\n"
    "_path(ax, coords_cache[demo_fname], JAWLINE, '#777777', lw=1.2, alpha=0.60, close=True)\n"
    "_path(ax, coords_cache[demo_fname], L_EYE,  ORGAN_COLORS['left_eye'],  lw=1.1, alpha=0.75, close=True)\n"
    "_path(ax, coords_cache[demo_fname], R_EYE,  ORGAN_COLORS['right_eye'], lw=1.1, alpha=0.75, close=True)\n"
    "_path(ax, coords_cache[demo_fname], M_OUT,  ORGAN_COLORS['mouth'],     lw=1.1, alpha=0.75, close=True)\n"
    "_path(ax, coords_cache[demo_fname], NOSE_B, ORGAN_COLORS['nose'],      lw=1.0, alpha=0.65)\n"
    "ax.set_aspect('equal'); ax.set_xticks([]); ax.set_yticks([])\n"
    "for sp in ax.spines.values(): sp.set_visible(False)\n"
    "ax.set_title('Graph Map (transparent — overlay-ready)', fontsize=9, loc='left')\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(f'{SAVE_DIR}/step6_test_face.pdf')\n"
    "plt.savefig(f'{SAVE_DIR}/step6_test_face.png')\n"
    "plt.savefig(f'{SAVE_DIR}/step6_test_face_graphmap.png', transparent=True)\n"
    "plt.show()\n"
    "print('Saved: step6_test_face.pdf + .png  +  step6_test_face_graphmap.png')"
))

# ── STEP 7: PER-ORGAN GRAPHS ──────────────────────────────────────────────
cells.append(md(
    "## Step ⑦ : Per-Organ Landmark Subgraphs\n\n"
    "Each organ is an independent subgraph of the full 468-node face. "
    "In the model these are **fully-connected GAT subgraphs**; here we show k-NN edges for clarity."
))
cells.append(code(
    "fig = plt.figure(figsize=(16, 5.0))\n"
    "fig.suptitle(\n"
    "    f'Step ⑦  |  Per-Organ Landmark Subgraphs  (→ {demo_fname})\\n'\n"
    "    'Each organ processed independently by an OrganGAT sub-network',\n"
    "    fontsize=9, fontweight='bold', y=1.02)\n"
    "\n"
    "gs = gridspec.GridSpec(1, 5, figure=fig, wspace=0.12)\n"
    "c  = coords_cache[demo_fname]\n"
    "\n"
    "for col, organ in enumerate(ORGAN_INDICES.keys()):\n"
    "    ax      = fig.add_subplot(gs[0, col])\n"
    "    n_nodes = len([i for i in ORGAN_INDICES[organ] if i < 468])\n"
    "    draw_organ(ax, c, organ, ms=5.5,\n"
    "               title=f'{ORGAN_LABELS[organ]}\\n{n_nodes} nodes')\n"
    "    ax.set_facecolor('#FAFAFA')\n"
    "    ax.text(0.5, -0.12, f'Score: {demo_scores[organ]:.2f}',\n"
    "            transform=ax.transAxes, fontsize=9, ha='center',\n"
    "            color=ORGAN_COLORS[organ], fontweight='bold')\n"
    "\n"
    "plt.savefig(f'{SAVE_DIR}/step7_organ_graphs.pdf')\n"
    "plt.savefig(f'{SAVE_DIR}/step7_organ_graphs.png')\n"
    "plt.show()\n"
    "print('Saved: step7_organ_graphs.pdf + .png')"
))

# ── STEPS 8+9: HISTOGRAMS ─────────────────────────────────────────────────
cells.append(md(
    "## Steps ⑧+⑨ : Per-Organ Projection Histograms + Test Face Rank\n\n"
    "For each organ *o*, collect all training-face projections, "
    "then locate the test face using `bisect.bisect_left`.\n\n"
    "`rank = bisect_left(sorted_projections, test_proj) / N`  \n"
    "`pseudo_score = clip(1 + 4 × rank, 1, 5)`"
))
cells.append(code(
    "fig, axes = plt.subplots(1, 5, figsize=(18, 5))\n"
    "fig.suptitle(\n"
    "    'Steps ⑧+⑨  |  Per-Organ Projection Distribution (all training faces)\\n'\n"
    "    'Red line = test face position  |  shaded = rank  |  '\n"
    "    'score = clip(1 + 4 × rank, 1, 5)',\n"
    "    fontsize=9, fontweight='bold', y=1.02)\n"
    "\n"
    "for col, organ in enumerate(ORGAN_INDICES.keys()):\n"
    "    ax        = axes[col]\n"
    "    all_p     = organ_projs[organ]\n"
    "    test_p    = demo_projs[organ]\n"
    "    rank_val  = bisect.bisect_left(organ_sorted[organ], test_p) / len(all_p)\n"
    "    score_val = demo_scores[organ]\n"
    "    col_o     = ORGAN_COLORS[organ]\n"
    "\n"
    "    cnts, edges, patches_h = ax.hist(\n"
    "        all_p, bins=40, color=col_o, alpha=0.80,\n"
    "        edgecolor='white', lw=0.3, zorder=2)\n"
    "\n"
    "    # Color bars below test face\n"
    "    mid = (edges[1] - edges[0]) / 2\n"
    "    for patch, left in zip(patches_h, edges[:-1]):\n"
    "        if left + mid < test_p:\n"
    "            patch.set_facecolor(col_o); patch.set_alpha(0.65)\n"
    "        else:\n"
    "            patch.set_facecolor('#DDDDDD'); patch.set_alpha(0.80)\n"
    "\n"
    "    y_max = cnts.max() if cnts.max() > 0 else 1\n"
    "    ax.axvline(test_p, color='#C62828', lw=2.5, zorder=5)\n"
    "\n"
    "    # Percentile reference lines\n"
    "    for pct, lbl in [(0.25, '25%'), (0.50, '50%'), (0.75, '75%')]:\n"
    "        pv = organ_sorted[organ][int(pct * len(organ_sorted[organ]))]\n"
    "        ax.axvline(pv, color='#AAAAAA', lw=0.8, ls='--', alpha=0.6)\n"
    "        ax.text(pv, -y_max*0.10, lbl, ha='center', fontsize=6, color='#999999')\n"
    "\n"
    "    ha_ann = 'left' if rank_val > 0.5 else 'right'\n"
    "    span   = edges[-1] - edges[0]\n"
    "    xoff   = test_p + span*0.02 if rank_val < 0.5 else test_p - span*0.02\n"
    "    ax.annotate(\n"
    "        f'rank = {rank_val:.1%}\\nscore = {score_val:.2f}',\n"
    "        xy=(test_p, y_max * 0.88),\n"
    "        xytext=(xoff, y_max * 0.88),\n"
    "        fontsize=8, color='#C62828', fontweight='bold', ha=ha_ann,\n"
    "        bbox=dict(boxstyle='round,pad=0.3', fc='white', ec='#C62828', alpha=0.88))\n"
    "\n"
    "    ax.set_xlabel('Projection  s(f, o)', fontsize=8)\n"
    "    ax.set_title(f'{ORGAN_LABELS[organ]}\\n{len(all_p)} training faces',\n"
    "                 fontsize=9, color=col_o, fontweight='bold', pad=3)\n"
    "    ax.set_ylim(-y_max*0.15, y_max*1.22)\n"
    "    for sp in ['top','right','left']:\n"
    "        ax.spines[sp].set_visible(False)\n"
    "    ax.yaxis.set_visible(False)\n"
    "\n"
    "plt.tight_layout(w_pad=0.5)\n"
    "plt.savefig(f'{SAVE_DIR}/step8_9_histograms.pdf')\n"
    "plt.savefig(f'{SAVE_DIR}/step8_9_histograms.png')\n"
    "plt.show()\n"
    "print('Saved: step8_9_histograms.pdf + .png')"
))

# ── STEP 10: FINAL SCORES ─────────────────────────────────────────────────
cells.append(md(
    "## Step ⑩ : Final Pseudo-Scores per Organ\n\n"
    "`p_{f,o} = 1 + 4 × rank_{f,o}  ∈ [1, 5]`\n\n"
    "This is the pseudo-label vector **p_f = [p_{f,LE}, p_{f,RE}, p_{f,N}, p_{f,M}, p_{f,J}]** "
    "used as per-organ beauty targets during training."
))
cells.append(code(
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5.5))\n"
    "fig.suptitle(\n"
    "    f'Step ⑩  |  Final Organ Pseudo-Scores  (→ {demo_fname})\\n'\n"
    "    f'p(f,o) = 1 + 4 × rank  ∈ [1,5]  |  GT Rating = {hol_ratings[demo_fname]:.3f}',\n"
    "    fontsize=9, fontweight='bold', y=1.02)\n"
    "\n"
    "organs = list(ORGAN_INDICES.keys())\n"
    "scores = [demo_scores[o] for o in organs]\n"
    "labels = [ORGAN_LABELS[o] for o in organs]\n"
    "colors = [ORGAN_COLORS[o] for o in organs]\n"
    "\n"
    "ax_bar = axes[0]\n"
    "bars = ax_bar.bar(range(len(organs)), scores, color=colors,\n"
    "                  linewidth=0, width=0.55, zorder=3)\n"
    "mean_sc = np.mean(scores)\n"
    "ax_bar.axhline(mean_sc, color='black', ls='--', lw=0.9, zorder=4,\n"
    "               label=f'Mean Pseudo = {mean_sc:.2f}')\n"
    "ax_bar.axhline(hol_ratings[demo_fname], color='0.45', ls=':', lw=0.9, zorder=4,\n"
    "               label=f'GT Rating = {hol_ratings[demo_fname]:.2f}')\n"
    "for bar, sc in zip(bars, scores):\n"
    "    ax_bar.text(bar.get_x() + bar.get_width()/2, sc + 0.05,\n"
    "               f'{sc:.2f}', ha='center', va='bottom', fontsize=8)\n"
    "ax_bar.set_xticks(range(len(organs)))\n"
    "ax_bar.set_xticklabels(labels, rotation=15, ha='right', fontsize=8)\n"
    "ax_bar.set_ylim(1, 5.5)\n"
    "ax_bar.set_ylabel('Pseudo-Score  p(f, o)')\n"
    "ax_bar.set_title(f'Organ Pseudo-Label Vector for {demo_fname}', loc='left')\n"
    "ax_bar.legend(loc='upper left', handlelength=1.8)\n"
    "ax_bar.yaxis.grid(True, zorder=0)\n"
    "ax_bar.set_axisbelow(True)\n"
    "\n"
    "# Summary table\n"
    "ax_tab = axes[1]\n"
    "ax_tab.axis('off')\n"
    "td = []\n"
    "for organ in organs:\n"
    "    proj  = demo_projs[organ]\n"
    "    rank  = bisect.bisect_left(organ_sorted[organ], proj) / len(organ_projs[organ])\n"
    "    score = demo_scores[organ]\n"
    "    td.append([ORGAN_LABELS[organ], f'{proj:.4f}', f'{rank:.1%}', f'{score:.2f}'])\n"
    "td.append(['Mean', '', '', f'{mean_sc:.2f}'])\n"
    "\n"
    "tbl = ax_tab.table(\n"
    "    cellText=td,\n"
    "    colLabels=['Organ', 'Projection', 'Rank', 'Score [1-5]'],\n"
    "    loc='center', cellLoc='center')\n"
    "tbl.auto_set_font_size(False); tbl.set_fontsize(10)\n"
    "tbl.scale(1.2, 1.9)\n"
    "for i, organ in enumerate(organs):\n"
    "    for j in range(4):\n"
    "        tbl[(i+1, j)].set_facecolor(ORGAN_COLORS[organ] + '22')\n"
    "for j in range(4):\n"
    "    tbl[(0, j)].set_facecolor('#E8EAF6')\n"
    "    tbl[(0, j)].set_text_props(fontweight='bold')\n"
    "ax_tab.set_title(\n"
    "    f'Pseudo-Label Summary\\n'\n"
    "    f'p_f = {[f\"{s:.2f}\" for s in scores]}',\n"
    "    fontsize=9, pad=12, fontweight='bold')\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(f'{SAVE_DIR}/step10_final_scores.pdf')\n"
    "plt.savefig(f'{SAVE_DIR}/step10_final_scores.png')\n"
    "plt.show()\n"
    "print('Saved: step10_final_scores.pdf + .png')"
))

# ── STEP 11: PCA PROJECTION ───────────────────────────────────────────────
cells.append(md(
    "## Step ⒪ : Geometric Projection onto Beauty Axis (PCA 2D)\n\n"
    "For each organ *o*:\n\n"
    "$$s_{f,o} = \\frac{(\\mathbf{x}_{f,o} - \\boldsymbol{\\mu}_{e,o}) \\cdot \\mathbf{v}_{e,o}}"
    "{\\|\\mathbf{v}_{e,o}\\|}$$\n\n"
    "PCA reduces the flattened organ coordinates to 2D so we can visualize: "
    "population distribution (colored dots), beauty axis arrow (orange), "
    "and the perpendicular projection of the test face (dashed red line)."
))
cells.append(code(
    "eth_pca  = demo_eth\n"
    "mu_pca   = pop_mean[eth_pca]\n"
    "proto_pca = beauty_proto[eth_pca]\n"
    "axis_pca  = beauty_axis[eth_pca]\n"
    "\n"
    "eth_fnames_pca  = [f for f in valid_train if get_eth(f) == eth_pca]\n"
    "eth_ratings_pca = np.array([hol_ratings[f] for f in eth_fnames_pca])\n"
    "\n"
    "fig, axes = plt.subplots(1, 5, figsize=(19, 5))\n"
    "fig.suptitle(\n"
    "    f'Step ⒪  |  Per-Organ Projection onto Beauty Axis  (ethnicity: {eth_pca})\\n'\n"
    "    '○ = pop. mean  |  ★ = beauty prototype  |  ◆ = test face  |  '\n"
    "    '→ = beauty axis  |  color = holistic rating',\n"
    "    fontsize=11, fontweight='bold', y=1.05)\n"
    "\n"
    "for col, organ in enumerate(ORGAN_INDICES.keys()):\n"
    "    ax   = axes[col]\n"
    "    idxs = [i for i in ORGAN_INDICES[organ] if i < 468]\n"
    "\n"
    "    organ_feats = np.array(\n"
    "        [coords_cache[f][idxs].ravel() for f in eth_fnames_pca])\n"
    "    pca    = PCA(n_components=2, random_state=42)\n"
    "    pts_2d = pca.fit_transform(organ_feats)\n"
    "\n"
    "    mu_2d    = pca.transform(mu_pca[idxs].ravel().reshape(1,-1))[0]\n"
    "    proto_2d = pca.transform(proto_pca[idxs].ravel().reshape(1,-1))[0]\n"
    "    demo_2d  = pca.transform(\n"
    "        coords_cache[demo_fname][idxs].ravel().reshape(1,-1))[0]\n"
    "\n"
    "    # Beauty axis in PCA space\n"
    "    ax_feat_pt = (axis_pca[idxs].ravel() + mu_pca[idxs].ravel()).reshape(1,-1)\n"
    "    axis_2d    = pca.transform(ax_feat_pt)[0] - mu_2d\n"
    "    axis_norm  = np.linalg.norm(axis_2d)\n"
    "    axis_unit  = axis_2d / axis_norm if axis_norm > 1e-9 else np.array([1.,0.])\n"
    "\n"
    "    # Scatter: training faces colored by rating\n"
    "    ax.scatter(pts_2d[:,0], pts_2d[:,1], c=eth_ratings_pca,\n"
    "               cmap='RdYlGn', s=7, alpha=0.40,\n"
    "               vmin=1, vmax=5, zorder=2, linewidths=0)\n"
    "\n"
    "    span    = max(pts_2d[:,0].ptp(), pts_2d[:,1].ptp(), 1e-6)\n"
    "    arr_len = span * 0.30\n"
    "    ax.annotate('',\n"
    "                xy=(mu_2d[0]+axis_unit[0]*arr_len,\n"
    "                    mu_2d[1]+axis_unit[1]*arr_len),\n"
    "                xytext=(mu_2d[0]-axis_unit[0]*arr_len*0.25,\n"
    "                        mu_2d[1]-axis_unit[1]*arr_len*0.25),\n"
    "                arrowprops=dict(arrowstyle='->', color='#FF6B35',\n"
    "                                lw=2.5, alpha=0.9))\n"
    "    ax.text(mu_2d[0]+axis_unit[0]*arr_len*1.20,\n"
    "            mu_2d[1]+axis_unit[1]*arr_len*1.20,\n"
    "            'Beauty\\nAxis', fontsize=6.5, color='#FF6B35',\n"
    "            fontweight='bold', ha='center')\n"
    "\n"
    "    # Key markers\n"
    "    ax.scatter(*mu_2d,    c='#222222', s=100, zorder=5, marker='o',\n"
    "               edgecolors='white', linewidths=1.5)\n"
    "    ax.scatter(*proto_2d, c='gold',    s=180, zorder=6, marker='*',\n"
    "               edgecolors='#E65100', linewidths=1.5)\n"
    "    ax.scatter(*demo_2d,  c='#C62828', s=130, zorder=7, marker='D',\n"
    "               edgecolors='white', linewidths=1.5)\n"
    "\n"
    "    # Perpendicular projection line\n"
    "    offset   = demo_2d - mu_2d\n"
    "    proj_sc  = np.dot(offset, axis_unit)\n"
    "    proj_pt  = mu_2d + proj_sc * axis_unit\n"
    "    ax.plot([demo_2d[0], proj_pt[0]], [demo_2d[1], proj_pt[1]],\n"
    "            color='#C62828', ls='--', lw=1.3, alpha=0.80, zorder=4)\n"
    "    ax.scatter(*proj_pt, c='#C62828', s=70, zorder=5,\n"
    "               marker='|', linewidths=2.5, alpha=0.9)\n"
    "\n"
    "    ev = pca.explained_variance_ratio_\n"
    "    ax.set_xlabel(f'PC1 ({ev[0]:.0%})', fontsize=7)\n"
    "    ax.set_ylabel(f'PC2 ({ev[1]:.0%})', fontsize=7)\n"
    "    ax.tick_params(labelsize=6)\n"
    "    ax.set_title(\n"
    "        f'{ORGAN_LABELS[organ]}\\n'\n"
    "        f'proj={demo_projs[organ]:.4f}  score={demo_scores[organ]:.2f}',\n"
    "        fontsize=9, color=ORGAN_COLORS[organ], fontweight='bold', pad=3)\n"
    "    ax.spines['top'].set_visible(False)\n"
    "    ax.spines['right'].set_visible(False)\n"
    "    if col == 0:\n"
    "        from matplotlib.lines import Line2D\n"
    "        leg = [\n"
    "            Line2D([0],[0], marker='o', color='w', markerfacecolor='#222', ms=7,\n"
    "                   label='Pop. Mean'),\n"
    "            Line2D([0],[0], marker='*', color='w', markerfacecolor='gold', ms=10,\n"
    "                   label='Beauty Proto.'),\n"
    "            Line2D([0],[0], marker='D', color='w', markerfacecolor='#C62828', ms=7,\n"
    "                   label='Test Face'),\n"
    "            mpatches.Patch(color='#FF6B35', label='Beauty Axis →'),\n"
    "        ]\n"
    "        ax.legend(handles=leg, fontsize=6, loc='upper left',\n"
    "                  framealpha=0.9, handlelength=1.2)\n"
    "\n"
    "sm = ScalarMappable(cmap='RdYlGn', norm=Normalize(vmin=1, vmax=5))\n"
    "sm.set_array([])\n"
    "cbar = plt.colorbar(sm, ax=axes, shrink=0.75, pad=0.01,\n"
    "                    label='Holistic Rating', aspect=25)\n"
    "cbar.ax.tick_params(labelsize=7)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(f'{SAVE_DIR}/step11_projection_pca.pdf')\n"
    "plt.savefig(f'{SAVE_DIR}/step11_projection_pca.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved: step11_projection_pca.pdf + .png')"
))

# ── SUMMARY ────────────────────────────────────────────────────────────────
cells.append(md("## Summary"))
cells.append(code(
    "import glob\n"
    "print('=' * 60)\n"
    "print('  Beauty-Axis Pseudo-Label Visualization: Summary')\n"
    "print('=' * 60)\n"
    "print(f'  Demo face : {demo_fname}')\n"
    "print(f'  Ethnicity : {demo_eth}   |   GT Rating : {hol_ratings[demo_fname]:.3f}')\n"
    "print()\n"
    "print(f'  {\"Organ\":<14} {\"Projection\":>12}  {\"Percentile\":>12}  {\"Score\":>7}')\n"
    "print('  ' + '-' * 50)\n"
    "for organ in ORGAN_INDICES:\n"
    "    proj  = demo_projs[organ]\n"
    "    rank  = bisect.bisect_left(organ_sorted[organ], proj) / len(organ_projs[organ])\n"
    "    score = demo_scores[organ]\n"
    "    print(f'  {ORGAN_LABELS[organ]:<14} {proj:>12.4f}  {rank:>11.2%}  {score:>7.2f}')\n"
    "print('  ' + '-' * 50)\n"
    "print(f'  {\"Mean\":<14} {\"\":>12}  {\"\":>12}  '\n"
    "      f'{np.mean(list(demo_scores.values())):>7.2f}')\n"
    "print()\n"
    "print(f'Figures in: {os.path.abspath(SAVE_DIR)}/')\n"
    "for fp in sorted(glob.glob(f'{SAVE_DIR}/*.png')):\n"
    "    print(f'  {os.path.basename(fp)}')\n"
    "print('\\nAll done!')"
))

# ── WRITE NOTEBOOK ─────────────────────────────────────────────────────────
notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0",
        },
    },
    "cells": cells,
}

out = "visualisation_pseudo_label.ipynb"
with open(out, "w", encoding="utf-8") as fh:
    json.dump(notebook, fh, indent=1, ensure_ascii=False)

print(f"Written: {out}  ({os.path.getsize(out):,} bytes)")
